### ISSUE TITLE
Deploy Serum DEX Using Compiler Optimizations

### ISSUE THREAD

**Issue by bonedaddy** [project-serum/serum-dex#186]
If the DEX program is deployed using the following compiler optimizations, overall compute usage should decrease significantly when interacting with the DEX. This will increase build times, but it should be a pretty decent improvement in terms of compute units consumed.

```toml
[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
```
